[CmdletBinding()]
param(
    [string]$VnrDir,
    [string]$RbmDir,
    [string]$ModDir
)

$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot "UpstreamCommon.ps1")

$RepoDir = Split-Path -Parent $PSScriptRoot
$manifest = Get-UpstreamManifest

function Write-Step { param([string]$msg) Write-Host "`n==> $msg" -ForegroundColor Cyan }
function Write-Ok   { param([string]$msg) Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Info { param([string]$msg) Write-Host "  [INFO] $msg" -ForegroundColor Gray }

if (-not $VnrDir) { $VnrDir = Get-UpstreamModDir -Id $manifest.mods.vnr.id -ModDir $ModDir }
if (-not $RbmDir) { $RbmDir = Get-UpstreamModDir -Id $manifest.mods.rbm.id -ModDir $ModDir }

if (-not $VnrDir -or -not (Test-Path -LiteralPath $VnrDir)) {
    throw "$($manifest.mods.vnr.name) ($($manifest.mods.vnr.id)) not found. Subscribe to it or pass -VnrDir."
}
if (-not $RbmDir -or -not (Test-Path -LiteralPath $RbmDir)) {
    throw "$($manifest.mods.rbm.name) ($($manifest.mods.rbm.id)) not found. Subscribe to it or pass -RbmDir."
}

$sourceRoots = @{ vnr = $VnrDir; rbm = $RbmDir }

Write-Step "Copying upstream files listed in upstream-manifest.json..."
Write-Info "VNR: $VnrDir"
Write-Info "RBM: $RbmDir"

$copied = 0
$unchanged = 0
foreach ($entry in $manifest.files) {
    $relative = $entry.path -replace '/', '\'
    $source = Join-Path $sourceRoots[$entry.source] $relative
    $target = Join-Path $RepoDir $relative

    if (-not (Test-Path -LiteralPath $source)) {
        throw "Upstream file missing from $($entry.source): $($entry.path)"
    }

    $targetDir = Split-Path -Parent $target
    if (-not (Test-Path -LiteralPath $targetDir)) {
        New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    }

    $bytes = [System.IO.File]::ReadAllBytes($source)
    # Clausewitz script files must not carry a BOM; textures are copied untouched.
    if ($relative -match '\.(gui|gfx|txt)$' -and $bytes.Length -ge 3 -and
        $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
        $bytes = $bytes[3..($bytes.Length - 1)]
    }

    if ((Test-Path -LiteralPath $target) -and
        [System.Linq.Enumerable]::SequenceEqual([byte[]]$bytes, [System.IO.File]::ReadAllBytes($target))) {
        $unchanged++
        continue
    }

    [System.IO.File]::WriteAllBytes($target, [byte[]]$bytes)
    Write-Info "updated $($entry.path)"
    $copied++
}
Write-Ok "$copied file(s) updated, $unchanged already current."

Write-Step "Generating $($manifest.generatedGfx)..."
$blocks = Get-CompatSpriteBlocks -VnrRoot $VnrDir -RbmRoot $RbmDir -AlwaysRedeclare $manifest.alwaysRedeclare

$out = [System.Collections.Generic.List[string]]::new()
$out.Add("# Generated by tools/Sync-Upstream.ps1. Do not edit by hand.")
$out.Add("# Re-declares, with Vanilla Navy Rework's definitions, every sprite that RBM's GFX Overhaul also defines.")
$out.Add("spriteTypes = {")
foreach ($block in $blocks) {
    $out.Add("")
    $blockLines = @($block -split "`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ })
    for ($i = 0; $i -lt $blockLines.Count; $i++) {
        $indent = if ($i -eq 0 -or $i -eq $blockLines.Count - 1) { "`t" } else { "`t`t" }
        $out.Add($indent + $blockLines[$i])
    }
}
$out.Add("}")
$out.Add("")

$gfxTarget = Join-Path $RepoDir ($manifest.generatedGfx -replace '/', '\')
$gfxDir = Split-Path -Parent $gfxTarget
if (-not (Test-Path -LiteralPath $gfxDir)) {
    New-Item -ItemType Directory -Path $gfxDir -Force | Out-Null
}
[System.IO.File]::WriteAllText($gfxTarget, ($out -join "`r`n"), [System.Text.UTF8Encoding]::new($false))
Write-Ok "$($blocks.Count) sprite definition(s) written."
